### ISSUE TITLE
Compatible with Omeka's Image Annotation plugin?

### ISSUE THREAD

**Issue by mackenziekbrooks** [CPHDH/theme-curatescape#6] opened 2018-02-28 20:59 UTC
I'm working with a class that would like to use the image annotation plugin within Curatescape. While I know that traditional Omeka exhibits aren't really part of the Curatescape architecture, I am able to use the plugin in the dashboard. However, in the public view, the annotations don't show up. It seems like the image annotation css/js aren't getting added to the page, though the html does contain the annotations. [Example](http://mackenziekbrooks.info/curatescapedemo/exhibits/show/test/image). Is there a way to get Curatescape to stop ignoring this plugin? Thanks!

**Comment by csudigitalhumanities** [comment] 2018-02-28 21:11
Hi @mackenziekbrooks, 

The Curatescape theme is designed for a specific use case and is not compatible with some types of Omeka plugins _by design_. 

By the way, it appears you're using an old version of the theme. Updating to the most recent version is recommended. It won't fix your specific issue but it does address a lot of old bugs, etc. 

Also, you may encounter issues when running Omeka in a subdirectory (i.e `mackenziekbrooks.info/curatescapedemo`), so I'd also recommend switching to a dedicated domain or subdomain (e.g. `curatescapedemo.mackenziekbrooks.info`). 

Making these two changes may actually _help_ solve your problem (though you might still need to do some debugging to figure out what isn't loading as expected).

Cheers -- Erin

PS: The Curatescape forum is generally the best place for questions: http://forum.curatescape.org/

**Closed as completed by csudigitalhumanities** 2018-02-28 21:11 UTC

**Comment by mackenziekbrooks** [comment] 2018-02-28 21:47
Thanks for the quick reply. I've tried the plugin in a fresh install/subdomain and it doesn't work there either so I'll continue debugging.
